name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create or update environment.prod.ts
        run: |
            echo "export const environment = {" > src/environments/environment.prod.ts
            echo "  apiUrl: '${{ secrets.API_URL }}'," >> src/environments/environment.prod.ts
            echo "  production: true," >> src/environments/environment.prod.ts
            echo "};" >> src/environments/environment.prod.ts
            cat src/environments/environment.prod.ts

      - name: Build Docker image
        run: |
          docker build -t buzzter100/busarov-fe:latest .
      - name: Push Docker image
        run: |
          docker push buzzter100/busarov-fe:latest
